apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-exporter-vol
  namespace: exporter
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/sonar-exporter-vol/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-exporter-pvc
  namespace: exporter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: sonar-exporter-vol
  resources:
    requests:
      storage: 2Gi